rosbag:
    step_size: 2
    series_size: 15
    depth_topic: '/hsrb/head_rgbd_sensor/depth_registered/image_raw'
    rgb_topic: '/hsrb/head_rgbd_sensor/rgb/image_raw'
    tf_topic: '/tf'
    data_folder: '/home/v4r/data/'
    bag_file: '/home/v4r/data/rosbag.bag'
    table_txt_file: '/home/v4r/data/txt/table.txt'

table_viewpoint:
    contour_approx_param: 0.1
    viewpoint_edge_dist: 0.55 #viewpoint will be created 20cm away from table edge
    viewpoint_dist_param: 0.4
    check_plan: False

table_extractor:
    normals_thresh: 0.2 #used to filter out points that don't belong to horizontal planes. 
                        #If |x| or |y| of the normal is bigger than the threshold, the point is removed from the cloud. 
    reconstruction_file: "/home/v4r/data/reconstruction.ply"
    downsample_vox_size: 0.02 # voxel size for downsampling
    remove_radius_outlier_nbpoints: 4 #12
    remove_radius_outlier_radius:  0.05 #0.1
    cluster_dbscan_eps: 0.2 #0.05 # 0.1 # Density parameter that is used to find neighbouring points.
    cluster_dbscan_minpoints: 10 #20 Minimum number of points to form a cluster.
    min_cluster_size_param: 0.015 # minimum 1% of pointcloud have to be in plane 
    map_height: 500
    map_width: 500
    map_deltax: 10.0
    map_deltay: 8.0
    map_resolution: 0.03
    class_labels: [2,3,5,6,9,11,13,14,31,37,38]
    class_names: ['cabinet', 'bed', 'sofa', 'table', 
        'bookshelf','counter', 'desk', 'shelves', 
        'night stand', 'otherstructure', 'otherfurn'] 
    colors: [[190, 153, 112],  # wall 0
    [189, 198, 255],  # floor 1
    [213, 255, 0],  # cabinet 2
    [158, 0, 142],  # bed 3
    [152, 255, 82],  # chair 4
    [119, 77, 0],  # sofa 5
    [122, 71, 130],  # table 6
    [0, 174, 126],  # door 7
    [0, 125, 181],  # window 8
    [0, 143, 156],  # bookshelf 9
    [107, 104, 130],  # picture 10
    [255, 229, 2],  # counter 11
    [117, 68, 177],  # blinds 12
    [1, 255, 254],  # desk 13
    [0, 21, 68],  # shelves 14
    [255, 166, 254],  # curtain 15
    [194, 140, 159],  # dresser 16
    [98, 14, 0],  # pillow 17
    [0, 71, 84],  # mirror 18
    [255, 219, 102],  # floor mat 19
    [0, 118, 255],  # clothes 20
    [67, 0, 44],  # ceiling 21
    [1, 208, 255],  # books 22
    [232, 94, 190],  # refrigerator 23
    [145, 208, 203],  # television 24
    [255, 147, 126],  # paper 25
    [95, 173, 78],  # towel 26
    [0, 100, 1],  # shower curtain 27
    [255, 238, 232],  # box 28
    [0, 155, 255],  # whiteboard 29
    [255, 0, 86],  # person 30
    [189, 211, 147],  # night stand 31
    [133, 169, 0],  # toilet 32 
    [149, 0, 58],  # sink 33
    [255, 2, 157],  # lamp 34
    [187, 136, 0],  # bathtub 35
    [0, 185, 23],  # bag 36
    [1, 0, 103],  # otherstructure 37
    [0, 0, 255],  # otherfurn 38
    [255, 0, 246]] # otherprop 39

camera_info:
    header: 
    seq: 332450
    stamp: 
        secs: 1567875018
        nsecs: 437901012
    frame_id: "head_rgbd_sensor_rgb_frame"
    height: 480
    width: 640
    distortion_model: "plumb_bob"
    D: [0.06221163438504582, -0.2196314239325009, -0.0001152980004131749, -0.0009528280601941514, 0.15652471413909]
    K: [538.391033533567, 0.0, 315.3074696331638, 0.0, 538.085452058436, 233.0483557773859, 0.0, 0.0, 1.0]
    R: [1.0, 0.0, 0.0, 0.0, 1.0, 0.0, 0.0, 0.0, 1.0]
    P: [538.391033533567, 0.0, 315.3074696331638, 0.0, 0.0, 538.085452058436, 233.0483557773859, 0.0, 0.0, 0.0, 1.0, 0.0]
    binning_x: 0